#define BRI_HW_PWR_BOARD 7
#define BRI_HW_PWR_PICO 8
#define BRI_HW_PWR_GPIO 9
#define BRI_HW_PWR_MAIN_A 10
#define BRI_HW_PWR_MAIN_B 11
#define BRI_HW_STATUS_NEOPIXELS_PIN 15
#define BRI_HW_STATUS_NEOPIXELS_CNT 3
#define BRI_HW_USER_RESET 22
#define BRI_HW_SERIAL_SPEED 9600

#define BRI_PUBLIC_TEAM_NUMBER "1234"
#define BRI_PUBLIC_HTTP_SERVER "http://192.168.16.10:8080/"
#define BRI_PUBLIC_MQTT_BROKER "192.168.16.10"

#define BRI_PUBLIC_MILLIS_WATCHDOG 15000
// set the next two in secret.h if you like
#define BRI_PRIVATE_WIFI_SSID ""
#define BRI_PRIVATE_WIFI_PSK ""
