NET_SEARCH
NET_CONNECT_WIFI
NET_CONNECT_WAIT_WIFI
NET_CONNECT_WAIT_ENET
NET_FMS_DISCOVER
NET_CONNECT_MQTT
NET_RUNNING


NET_SEARCH -> NET_CONNECT_WAIT_ENET : link
NET_CONNECT_WAIT_ENET -> NET_SEARCH : dhcp fails
NET_CONNECT_WAIT_ENET -> NET_FMS_DISCOVER : dhcp success
NET_SEARCH -> NET_CONNECT_WIFI -> NET_CONNECT_WAIT_WIFI
NET_CONNECT_WAIT_WIFI -> NET_FMS_DISCOVER : have IP
NET_FMS_DISCOVER -> NET_CONNECT_MQTT : cfg.mqttBroker is IP
NET_CONNECT_MQTT -> NET_RUNNING : Wait for success

NET_RUNNING -> NET_CONNECT_MQTT : mqtt timeout

NET_RUNNING -> NET_SEARCH : wifi not connected
NET_FMS_DISCOVER -> NET_SEARCH : if link down
NET_CONNECT_WAIT_WIFI -> NET_SEARCH : timeout
NET_RUNNING -> NET_SEARCH : ethernet no-link
NET_CONNECT_MQTT -> NET_SEARCH : no-link
NET_RUNNING -> NET_SEARCH : Ethernet link up and currently on wifi
NET_FMS_DISCOVER -> NET_SEARCH : Ethernet link up and currently on wifi
NET_CONNECT_MQTT -> NET_SEARCH : Ethernet link up and currently on wifi
